# Refresh the raw Codex model catalog and publish an OmniRoute-safe snapshot.
# Run without Codex open to refresh through Codex's authenticated model flow:
#   .\Refresh-ModelCatalog.ps1
# Filter the currently saved raw catalog without refreshing it:
#   .\Refresh-ModelCatalog.ps1 -FromExistingCatalog

[CmdletBinding()]
param(
    [string]$CustomProviderId = 'omniroute',
    [switch]$FromExistingCatalog
)

$ErrorActionPreference = 'Stop'

$codexHomeDir = if ([string]::IsNullOrWhiteSpace($env:CODEX_HOME)) {
    Join-Path $env:USERPROFILE '.codex'
} else {
    [System.IO.Path]::GetFullPath($env:CODEX_HOME)
}

$configPath = Join-Path $codexHomeDir 'config.toml'
$cachePath = Join-Path $codexHomeDir 'models_cache.json'
$cacheBackupPath = Join-Path $codexHomeDir 'models_cache.json.catalog-refresh-backup'
$configBackupPath = Join-Path $codexHomeDir 'config.toml.catalog-refresh-backup'
$rawCatalogPath = Join-Path $codexHomeDir 'openai-models-cache.json'
$omniRouteCatalogPath = Join-Path $codexHomeDir 'omniroute-models-catalog.json'
$customProfileName = 'custom-model-catalog'
$customProfilePath = Join-Path $codexHomeDir "$customProfileName.config.toml"
$profileMarker = '# Generated by Refresh-ModelCatalog.ps1'
$temporaryConfigMarker = '# Temporary config from Refresh-ModelCatalog.ps1'

if (-not (Test-Path -LiteralPath $configPath -PathType Leaf)) {
    throw "Codex config was not found: $configPath"
}

if (Test-Path -LiteralPath $configBackupPath -PathType Leaf) {
    $currentConfig = [System.IO.File]::ReadAllText($configPath)
    if ($currentConfig.Contains($temporaryConfigMarker)) {
        Remove-Item -LiteralPath $configPath -Force
        Move-Item -LiteralPath $configBackupPath -Destination $configPath
        throw 'Recovered config.toml after an interrupted refresh. Run the refresh again.'
    }
    throw "A refresh recovery file exists; inspect it before continuing: $configBackupPath"
}

if (Test-Path -LiteralPath $cacheBackupPath -PathType Leaf) {
    if (Test-Path -LiteralPath $cachePath -PathType Leaf) {
        Remove-Item -LiteralPath $cachePath -Force
    }
    Move-Item -LiteralPath $cacheBackupPath -Destination $cachePath
    throw 'Recovered models_cache.json after an interrupted refresh. Run the refresh again.'
}

if ([string]::IsNullOrWhiteSpace($CustomProviderId) -or
    $CustomProviderId -eq 'openai' -or
    $CustomProviderId -notmatch '^[A-Za-z0-9_.-]+$') {
    throw 'The provider ID must be a non-empty custom ID containing only letters, digits, periods, underscores, or hyphens.'
}

if (-not $FromExistingCatalog -and
    (Get-Process -Name 'codex', 'ChatGPT' -ErrorAction SilentlyContinue)) {
    throw 'Close Codex CLI and ChatGPT Desktop before refreshing the shared model cache.'
}

function Write-GeneratedProfile {
    param(
        [string]$Path,
        [string]$Content,
        [string]$OwnershipMarker
    )

    if (Test-Path -LiteralPath $Path -PathType Leaf) {
        $oldContent = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
        $legacyMarker = '# Generated by Refresh-CodexModelCatalog.ps1'
        if (-not $oldContent.Contains($OwnershipMarker) -and
            -not $oldContent.Contains($legacyMarker)) {
            throw "Profile already exists and is not managed by this script: $Path"
        }
    }

    $temporaryProfilePath = "$Path.$([guid]::NewGuid().ToString('N')).tmp"
    try {
        [System.IO.File]::WriteAllText(
            $temporaryProfilePath,
            $Content,
            [System.Text.UTF8Encoding]::new($false)
        )
        if (Test-Path -LiteralPath $Path -PathType Leaf) {
            [System.IO.File]::Move($temporaryProfilePath, $Path, $true)
        } else {
            [System.IO.File]::Move($temporaryProfilePath, $Path)
        }
    } finally {
        if (Test-Path -LiteralPath $temporaryProfilePath) {
            Remove-Item -LiteralPath $temporaryProfilePath -Force
        }
    }
}

function Publish-OmniRouteCatalog {
    param(
        [string]$SourcePath,
        [string]$TargetPath
    )

    if (-not (Test-Path -LiteralPath $SourcePath -PathType Leaf)) {
        throw "Raw model catalog was not found: $SourcePath"
    }

    $catalog = [System.Text.Json.Nodes.JsonNode]::Parse(
        [System.IO.File]::ReadAllText($SourcePath)
    )
    if ($null -eq $catalog -or $catalog['models'] -isnot [System.Text.Json.Nodes.JsonArray]) {
        throw 'The raw model catalog must contain a models array.'
    }

    $models = $catalog['models'].AsArray()
    $sourceSlugs = [System.Collections.Generic.List[string]]::new()
    foreach ($modelEntry in $models) {
        if ($null -eq $modelEntry -or $null -eq $modelEntry['slug']) {
            throw 'Every catalog model must have a slug.'
        }
        $sourceSlugs.Add($modelEntry['slug'].GetValue[string]())
    }

    if (-not $sourceSlugs.Contains('gpt-6-sol')) {
        throw 'The raw catalog does not contain the configured model gpt-6-sol.'
    }

    $expectedSlugs = $sourceSlugs.ToArray()
    $publishedSlugs = [System.Collections.Generic.List[string]]::new()
    foreach ($modelEntry in $models) {
        $publishedSlugs.Add($modelEntry['slug'].GetValue[string]())
    }
    if (($expectedSlugs -join "`n") -cne ($publishedSlugs.ToArray() -join "`n")) {
        throw 'Catalog validation failed: published model slugs do not match the raw catalog.'
    }
    if (-not $publishedSlugs.Contains('gpt-6-sol')) {
        throw 'Catalog validation failed: gpt-6-sol is missing.'
    }

    $jsonOptions = [System.Text.Json.JsonSerializerOptions]::new()
    $jsonOptions.WriteIndented = $true
    $catalogJson = $catalog.ToJsonString($jsonOptions)
    $targetDirectory = Split-Path -Parent $TargetPath
    $temporaryCatalogPath = Join-Path $targetDirectory (
        '.omniroute-models-catalog-' + [guid]::NewGuid().ToString('N') + '.tmp'
    )

    try {
        [System.IO.File]::WriteAllText(
            $temporaryCatalogPath,
            $catalogJson,
            [System.Text.UTF8Encoding]::new($false)
        )
        $validatedCatalog = [System.Text.Json.Nodes.JsonNode]::Parse(
            [System.IO.File]::ReadAllText($temporaryCatalogPath)
        )
        $validatedSlugs = @(
            $validatedCatalog['models'].AsArray() |
                ForEach-Object { $_['slug'].GetValue[string]() }
        )
        if (($expectedSlugs -join "`n") -cne ($validatedSlugs -join "`n") -or
            $validatedSlugs -cnotcontains 'gpt-6-sol') {
            throw 'The written OmniRoute catalog failed validation.'
        }

        $changed = $true
        if (Test-Path -LiteralPath $TargetPath -PathType Leaf) {
            $newHash = (Get-FileHash -LiteralPath $temporaryCatalogPath -Algorithm SHA256).Hash
            $oldHash = (Get-FileHash -LiteralPath $TargetPath -Algorithm SHA256).Hash
            if ($newHash -eq $oldHash) {
                $changed = $false
            } else {
                $stamp = [DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ')
                $targetBackupPath = "$TargetPath.bak.$stamp"
                [System.IO.File]::Replace($temporaryCatalogPath, $TargetPath, $targetBackupPath)
            }
        } else {
            [System.IO.File]::Move($temporaryCatalogPath, $TargetPath)
        }

        return [pscustomobject]@{
            source_count = $sourceSlugs.Count
            published_count = $publishedSlugs.Count
            includes_codex_auto_review = $publishedSlugs.Contains('codex-auto-review')
            changed = $changed
        }
    } finally {
        if (Test-Path -LiteralPath $temporaryCatalogPath) {
            Remove-Item -LiteralPath $temporaryCatalogPath -Force
        }
    }
}

$normalizedOmniRouteCatalogPath = $omniRouteCatalogPath.Replace('\', '/')
$profileContent = @"
$profileMarker
model_provider = "$CustomProviderId"
model_catalog_json = "$normalizedOmniRouteCatalogPath"
"@

if ($FromExistingCatalog) {
    $result = Publish-OmniRouteCatalog -SourcePath $rawCatalogPath -TargetPath $omniRouteCatalogPath
    Write-GeneratedProfile -Path $customProfilePath -Content $profileContent -OwnershipMarker $profileMarker
    Write-Output "Published OmniRoute catalog from the saved snapshot: $omniRouteCatalogPath"
    Write-Output "Models: $($result.source_count) -> $($result.published_count); codex-auto-review included: $($result.includes_codex_auto_review); changed: $($result.changed)"
    Write-Output "Generated profile: $customProfilePath"
    return
}

function Find-CodexCommand {
    $onPath = Get-Command codex -ErrorAction SilentlyContinue
    if ($onPath) {
        return $onPath.Source
    }

    $desktopBin = Join-Path $env:LOCALAPPDATA 'OpenAI\Codex\bin'
    if (Test-Path -LiteralPath $desktopBin -PathType Container) {
        $candidate = Get-ChildItem -LiteralPath $desktopBin -Filter 'codex.exe' -Recurse -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
        if ($candidate) {
            return $candidate.FullName
        }
    }

    $extensionRoot = Join-Path $env:USERPROFILE '.vscode\extensions'
    if (Test-Path -LiteralPath $extensionRoot -PathType Container) {
        $candidate = Get-ChildItem -LiteralPath $extensionRoot -Directory -Filter 'openai.chatgpt-*' -ErrorAction SilentlyContinue |
            Sort-Object Name -Descending |
            ForEach-Object { Join-Path $_.FullName 'bin\windows-x86_64\codex.exe' } |
            Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
            Select-Object -First 1
        if ($candidate) {
            return $candidate
        }
    }

    throw 'Could not find the codex executable. Install the Codex CLI or ChatGPT Desktop app.'
}

$codexCommand = Find-CodexCommand
Write-Output "Using codex: $codexCommand"
& $codexCommand --version
$startedAt = [DateTimeOffset]::UtcNow
$cacheWasPresent = Test-Path -LiteralPath $cachePath -PathType Leaf
$cacheWasMoved = $false
$configWasBackedUp = $false
$temporaryRawCatalogPath = Join-Path $codexHomeDir (
    '.openai-models-cache-' + [guid]::NewGuid().ToString('N') + '.json'
)

try {
    if ($cacheWasPresent) {
        Move-Item -LiteralPath $cachePath -Destination $cacheBackupPath
        $cacheWasMoved = $true
    }

    Copy-Item -LiteralPath $configPath -Destination $configBackupPath
    $configWasBackedUp = $true
    [System.IO.File]::WriteAllText(
        $configPath,
        "$temporaryConfigMarker`r`nmodel_provider = `"openai`"`r`n",
        [System.Text.UTF8Encoding]::new($false)
    )

    # This uses Codex's authenticated refresh path with the custom catalog out of scope.
    $null = & $codexCommand debug models
    if ($LASTEXITCODE -ne 0) {
        throw "codex debug models failed with exit code $LASTEXITCODE."
    }
    if (-not (Test-Path -LiteralPath $cachePath -PathType Leaf)) {
        throw 'Codex did not create models_cache.json. Check OpenAI login and network access.'
    }

    $freshCache = Get-Content -LiteralPath $cachePath -Raw -Encoding UTF8 | ConvertFrom-Json -ErrorAction Stop
    $fetchedAt = [DateTimeOffset]::Parse([string]$freshCache.fetched_at)
    if ($fetchedAt -lt $startedAt.AddSeconds(-10)) {
        throw 'The generated cache timestamp predates this refresh; refusing to publish it.'
    }
    if ([string]::IsNullOrWhiteSpace([string]$freshCache.client_version)) {
        throw 'The generated cache has no client_version; refusing to publish it.'
    }
    if (@($freshCache.models).Count -eq 0 -or
        @($freshCache.models | Where-Object { $_.slug -eq 'gpt-6-sol' }).Count -eq 0) {
        throw 'The generated cache is missing models or gpt-6-sol; refusing to publish it.'
    }

    [System.IO.File]::Copy($cachePath, $temporaryRawCatalogPath, $true)
    $sourceHash = (Get-FileHash -LiteralPath $cachePath -Algorithm SHA256).Hash
    $copyHash = (Get-FileHash -LiteralPath $temporaryRawCatalogPath -Algorithm SHA256).Hash
    if ($sourceHash -ne $copyHash) {
        throw 'The raw catalog copy did not match the refreshed Codex cache.'
    }

    if (Test-Path -LiteralPath $rawCatalogPath -PathType Leaf) {
        $stamp = [DateTime]::UtcNow.ToString('yyyyMMddTHHmmssZ')
        [System.IO.File]::Replace(
            $temporaryRawCatalogPath,
            $rawCatalogPath,
            "$rawCatalogPath.bak.$stamp"
        )
    } else {
        [System.IO.File]::Move($temporaryRawCatalogPath, $rawCatalogPath)
    }

    $result = Publish-OmniRouteCatalog -SourcePath $rawCatalogPath -TargetPath $omniRouteCatalogPath
    Write-GeneratedProfile -Path $customProfilePath -Content $profileContent -OwnershipMarker $profileMarker
    Write-Output "Updated raw catalog: $rawCatalogPath"
    Write-Output "Published OmniRoute catalog: $omniRouteCatalogPath"
    Write-Output "Models: $($result.source_count) -> $($result.published_count); codex-auto-review included: $($result.includes_codex_auto_review); changed: $($result.changed)"
    Write-Output "Generated profile: $customProfilePath"
} finally {
    if ($configWasBackedUp -and (Test-Path -LiteralPath $configBackupPath -PathType Leaf)) {
        if (Test-Path -LiteralPath $configPath -PathType Leaf) {
            $currentConfig = [System.IO.File]::ReadAllText($configPath)
            if (-not $currentConfig.Contains($temporaryConfigMarker)) {
                throw 'config.toml changed during refresh; preserved the backup for manual recovery.'
            }
            Remove-Item -LiteralPath $configPath -Force
        }
        Move-Item -LiteralPath $configBackupPath -Destination $configPath
    }

    if (Test-Path -LiteralPath $temporaryRawCatalogPath) {
        Remove-Item -LiteralPath $temporaryRawCatalogPath -Force
    }
    if ($cacheWasMoved -and (Test-Path -LiteralPath $cacheBackupPath -PathType Leaf)) {
        if (Test-Path -LiteralPath $cachePath -PathType Leaf) {
            Remove-Item -LiteralPath $cachePath -Force
        }
        Move-Item -LiteralPath $cacheBackupPath -Destination $cachePath
    } elseif (-not $cacheWasPresent -and (Test-Path -LiteralPath $cachePath -PathType Leaf)) {
        Remove-Item -LiteralPath $cachePath -Force
    }
}
