# Save as: $CODEX_HOME\Refresh-CodexModelCatalog.ps1
# Run with Codex closed:
#   .\Refresh-CodexModelCatalog.ps1
# If the custom provider is selected through a profile:
#   .\Refresh-CodexModelCatalog.ps1 -CustomProviderId <provider-id>
# Without -CustomProviderId the script prompts interactively;
# pressing Enter accepts the default provider ID 'omniroute'.

[CmdletBinding()]
param(
    [string]$CustomProviderId
)

$ErrorActionPreference = 'Stop'

$codexHomeDir = if ([string]::IsNullOrWhiteSpace($env:CODEX_HOME)) {
    Join-Path $env:USERPROFILE '.codex'
} else {
    [System.IO.Path]::GetFullPath($env:CODEX_HOME)
}

$configPath = Join-Path $codexHomeDir 'config.toml'
$cachePath = Join-Path $codexHomeDir 'models_cache.json'
$backupPath = Join-Path $codexHomeDir 'models_cache.json.catalog-refresh-backup'
$catalogPath = Join-Path $codexHomeDir 'openai-models-cache.json'
$customProfileName = 'custom-model-catalog'
$customProfilePath = Join-Path $codexHomeDir "$customProfileName.config.toml"
$marker = '# Generated by Refresh-CodexModelCatalog.ps1'

if (-not (Test-Path -LiteralPath $configPath -PathType Leaf)) {
    throw "Codex config was not found: $configPath"
}

if (Get-Process -Name 'codex', 'ChatGPT' -ErrorAction SilentlyContinue) {
    throw 'Close Codex CLI and ChatGPT Desktop before refreshing the shared model cache.'
}

# Recover the original cache if a previous run was interrupted.
if (Test-Path -LiteralPath $backupPath) {
    if (Test-Path -LiteralPath $cachePath) {
        Remove-Item -LiteralPath $cachePath -Force
    }
    Move-Item -LiteralPath $backupPath -Destination $cachePath
    throw 'Recovered the cache from an interrupted run. Run the refresh again.'
}

# Check config.toml for a forbidden root-level catalog setting.
$hasRootCatalog = $false
$insideTomlTable = $false

foreach ($line in [System.IO.File]::ReadLines($configPath)) {
    if ($line -match '^\s*\[') {
        $insideTomlTable = $true
    }
    if ($insideTomlTable) {
        continue
    }
    if ($line -match '^\s*model_catalog_json\s*=') {
        $hasRootCatalog = $true
    }
}

if ([string]::IsNullOrWhiteSpace($CustomProviderId)) {
    $answer = Read-Host 'Custom provider ID [omniroute]'
    $CustomProviderId = if ([string]::IsNullOrWhiteSpace($answer)) { 'omniroute' } else { $answer.Trim() }
}
if ($CustomProviderId -eq 'openai') {
    throw 'The custom provider ID cannot be ''openai''.'
}
if ($CustomProviderId -notmatch '^[A-Za-z0-9_.-]+$') {
    throw 'The provider ID may contain only letters, digits, periods, underscores, and hyphens.'
}
if ($hasRootCatalog) {
    throw 'Move the root-level model_catalog_json setting into the custom provider profile, then rerun.'
}

function Write-GeneratedProfile {
    param(
        [string]$Path,
        [string]$Content,
        [string]$OwnershipMarker
    )

    if (Test-Path -LiteralPath $Path -PathType Leaf) {
        $oldContent = Get-Content -LiteralPath $Path -Raw -Encoding UTF8
        if (-not $oldContent.Contains($OwnershipMarker)) {
            throw "Profile already exists and is not managed by this script: $Path"
        }
    }

    [System.IO.File]::WriteAllText(
        $Path,
        $Content,
        [System.Text.UTF8Encoding]::new($false)
    )
}

$normalizedCatalogPath = $catalogPath.Replace('\', '/')

Write-GeneratedProfile `
    -Path $customProfilePath `
    -OwnershipMarker $marker `
    -Content @"
$marker
model_provider = "$CustomProviderId"
model_catalog_json = "$normalizedCatalogPath"
"@

function Find-CodexCommand {
    # 1) PATH (npm/winget/manual install)
    $onPath = Get-Command codex -ErrorAction SilentlyContinue
    if ($onPath) {
        return $onPath.Source
    }

    # 2) Bundled with the ChatGPT Desktop app (MSIX): newest bin dir wins
    $desktopBin = Join-Path $env:LOCALAPPDATA 'OpenAI\Codex\bin'
    if (Test-Path -LiteralPath $desktopBin -PathType Container) {
        $candidate = Get-ChildItem -LiteralPath $desktopBin -Filter 'codex.exe' -Recurse -File -ErrorAction SilentlyContinue |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
        if ($candidate) {
            return $candidate.FullName
        }
    }

    # 3) ChatGPT VS Code extension
    $extRoot = Join-Path $env:USERPROFILE '.vscode\extensions'
    if (Test-Path -LiteralPath $extRoot -PathType Container) {
        $candidate = Get-ChildItem -LiteralPath $extRoot -Directory -Filter 'openai.chatgpt-*' -ErrorAction SilentlyContinue |
            Sort-Object Name -Descending |
            ForEach-Object { Join-Path $_.FullName 'bin\windows-x86_64\codex.exe' } |
            Where-Object { Test-Path -LiteralPath $_ -PathType Leaf } |
            Select-Object -First 1
        if ($candidate) {
            return $candidate
        }
    }

    throw 'Could not find the codex executable. Install the Codex CLI (npm i -g @openai/codex) or the ChatGPT Desktop app.'
}

$codexCommand = Find-CodexCommand
Write-Output "Using codex: $codexCommand"
& $codexCommand --version
$startedAt = [DateTimeOffset]::UtcNow
$cacheWasPresent = Test-Path -LiteralPath $cachePath -PathType Leaf
$cacheWasMoved = $false
$tempCatalogPath = Join-Path $codexHomeDir (
    '.openai-models-cache-' + [guid]::NewGuid().ToString('N') + '.json'
)

try {
    if ($cacheWasPresent) {
        Move-Item -LiteralPath $cachePath -Destination $backupPath
        $cacheWasMoved = $true
    }

    # This uses Codex's own authenticated refresh path. Do not add --bundled.
    $null = & $codexCommand debug models -c 'model_provider="openai"'
    if ($LASTEXITCODE -ne 0) {
        throw "codex debug models failed with exit code $LASTEXITCODE."
    }
    if (-not (Test-Path -LiteralPath $cachePath -PathType Leaf)) {
        throw 'Codex did not create models_cache.json. Check OpenAI login and network access.'
    }

    $freshCache = Get-Content -LiteralPath $cachePath -Raw -Encoding UTF8 | ConvertFrom-Json -ErrorAction Stop
    $fetchedAt = [DateTimeOffset]::Parse([string]$freshCache.fetched_at)

    if ($fetchedAt -lt $startedAt.AddSeconds(-10)) {
        throw 'The generated cache timestamp predates this refresh; refusing to publish it.'
    }
    if ([string]::IsNullOrWhiteSpace([string]$freshCache.client_version)) {
        throw 'The generated cache has no client_version; refusing to publish it.'
    }
    if (@($freshCache.models).Count -eq 0) {
        throw 'The generated cache contains no models; refusing to publish it.'
    }

    # Copy the entire cache without parsing and reserializing it.
    [System.IO.File]::Copy($cachePath, $tempCatalogPath, $true)

    $sourceHash = (Get-FileHash -LiteralPath $cachePath -Algorithm SHA256).Hash
    $copyHash = (Get-FileHash -LiteralPath $tempCatalogPath -Algorithm SHA256).Hash
    if ($sourceHash -ne $copyHash) {
        throw 'The catalog copy did not match the newly generated cache.'
    }

    if (Test-Path -LiteralPath $catalogPath -PathType Leaf) {
        $catalogBackupPath = "$catalogPath.bak.$([guid]::NewGuid().ToString('N'))"
        [System.IO.File]::Replace($tempCatalogPath, $catalogPath, $catalogBackupPath)
    } else {
        [System.IO.File]::Move($tempCatalogPath, $catalogPath)
    }

    Write-Output "Created full model cache snapshot: $catalogPath"
    Write-Output "Generated profile: $customProfilePath"
    Write-Output "Use the custom provider with: `"$codexCommand`" --profile $customProfileName"
} finally {
    if (Test-Path -LiteralPath $tempCatalogPath) {
        Remove-Item -LiteralPath $tempCatalogPath -Force
    }

    if ($cacheWasMoved -and (Test-Path -LiteralPath $backupPath)) {
        if (Test-Path -LiteralPath $cachePath) {
            Remove-Item -LiteralPath $cachePath -Force
        }
        Move-Item -LiteralPath $backupPath -Destination $cachePath
    } elseif (-not $cacheWasPresent -and (Test-Path -LiteralPath $cachePath)) {
        Remove-Item -LiteralPath $cachePath -Force
    }
}